![logo_usjt.png](https://www.usjt.br/app/themes/mobister/dist/images/sao-judas-universidade.png)

# Datawarehousing & Data Mining
- **Professor**: Sergio Bonato <antonio.bonato@saojudas.br>

# Atividade04 - NumPy Básico: Arrays e Processamento Vetorizado

**Conteúdo:**
- O que é NumPy; NumPy arrays; operações com arrays
- NumPy: matrizes e operações com matrizes
- NumPy: carregando dados com NumPy
- NumPy: álgebra linear básica

## Autor
**Aluno: Gustavo Favorito Demarchi**

**RA: 817123231**

Obs: esta atividade é individual.

## Exercícios

**1** Utilize o código dado para importar o arquivo `dados.csv`, que contém dados de saúde sobre homens e mulheres de diversas idades. Veja na tabela a descrição dos campos.

|Ordem|Campo|Descrição|
|:-|:-|:-|
|0|sexo|Homem=0 Mulher=1|
|1|idade|anos completos|
|2|rendom|renda domiciliar|
|3|anoest|anos de estudo|
|4|altura||
|5|peso||
|6|probagud|0 não teve problemas nos últimos 30 dias, 1 = teve problema nos últimos 30 dias|
|7|probcron|0 não tem problemas crônicos, 1 = tem problemas crônicos|
|8|gastorem|gasto com medicamentos nos últimos 30 dias|

Utilize o código pronto para importar os dados. Veja que o parâmetro `converters` da função `loadtxt` contém um dicionário que converte os dados faltantes para `nan` (not a number).

In [1]:
import numpy as np

#coloque aqui o caminho completo do arquivo
arquivo = 'dataset/dados.csv'
headers = np.array(['sexo', 'idade', 'rendom', 'anoest', 'altura', 'peso', 'probagud', 'probracron', 'gastorem'])
zera = lambda x: np.nan if len(x)==0 else x
conversores = {i:zera for i in range(9)}
arr = None
arr = np.loadtxt(arquivo, delimiter=';',dtype=np.float64, converters=conversores)

**a)** Imprima o formato do array arr.

In [2]:
arr.dtype

dtype('float64')

**b)** Imprima as 10 primeiras linhas do vetor e examine-as.

In [3]:
print(headers)
print(arr[:10])

['sexo' 'idade' 'rendom' 'anoest' 'altura' 'peso' 'probagud' 'probracron'
 'gastorem']
[[0.000e+00 4.000e+00 1.320e+02 1.000e+00 9.600e-01 1.500e+01 1.000e+00
  1.000e+00 4.600e+00]
 [0.000e+00 5.000e+01 1.089e+03 1.000e+00 1.690e+00 5.400e+01 1.000e+00
  0.000e+00 4.250e+00]
 [0.000e+00 1.100e+01 1.570e+02 2.000e+00 1.320e+00 2.700e+01 1.000e+00
  0.000e+00 5.000e+00]
 [0.000e+00 2.000e+00 1.570e+02 1.000e+00       nan 1.300e+01 1.000e+00
  0.000e+00 5.000e+00]
 [0.000e+00 1.000e+01 3.000e+02 3.000e+00 1.360e+00 4.300e+01 1.000e+00
  0.000e+00 2.000e+00]
 [0.000e+00 1.000e+00 9.410e+02 1.000e+00 8.500e-01 1.400e+01 1.000e+00
  0.000e+00 4.000e-01]
 [0.000e+00 5.500e+01 7.520e+02 1.000e+00 1.570e+00 5.400e+01 1.000e+00
  1.000e+00 7.000e-01]
 [0.000e+00 1.700e+01 7.520e+02 1.000e+00 1.560e+00 4.600e+01 1.000e+00
  0.000e+00 2.500e-01]
 [0.000e+00 4.800e+01 2.080e+02 1.000e+00 1.610e+00 5.800e+01 1.000e+00
  0.000e+00 1.000e+00]
 [0.000e+00 6.000e+00 6.430e+02 1.000e+00 1.060e+00 1.600e

**c)** Verifique se há colunas com dados nan. Quais são as colunas? Dicas: use o array headers definido no código dado, a ufunction `isnan()` e a função `any()`, um loop `for` e indexação booleana.

In [4]:
colunas_com_nan = [any(np.isnan(arr[:,col])) for col in range(arr.shape[1])]
headers[colunas_com_nan]

array(['altura', 'peso'], dtype='<U10')

**d)** Crie uma visão do array arr sem as linhas que contém anotações faltantes (dados nan).

In [5]:
print(len(arr))
print(len(arr[~np.isnan(arr).any(axis=1)]))
print(arr[~np.isnan(arr).any(axis=1)])

3897
3570
[[0.0000e+00 4.0000e+00 1.3200e+02 ... 1.0000e+00 1.0000e+00 4.6000e+00]
 [0.0000e+00 5.0000e+01 1.0890e+03 ... 1.0000e+00 0.0000e+00 4.2500e+00]
 [0.0000e+00 1.1000e+01 1.5700e+02 ... 1.0000e+00 0.0000e+00 5.0000e+00]
 ...
 [1.0000e+00 3.6000e+01 2.5911e+04 ... 0.0000e+00 0.0000e+00 4.0000e+01]
 [1.0000e+00 7.0000e+01 2.2538e+04 ... 0.0000e+00 1.0000e+00 3.0000e+01]
 [1.0000e+00 4.9000e+01 2.7510e+04 ... 1.0000e+00 1.0000e+00 3.4000e+01]]


**e)** Calcule a média de cada coluna da visão not_nan e atribua aos nan da coluna altura a média da altura e aos nan da coluna peso a média da coluna peso. Antes da trocar os nan, calcule a média das colunas de arr para ver o que acontece. 

Lembre-se de como funcionam os eixos! Abaixo um exemplo com a função `sum()`
![eixos](https://saskeli.github.io/data-analysis-with-python-summer-2019/_images/aggregation.svg)

In [6]:
arr = None
arr = np.loadtxt(arquivo, delimiter=';',dtype=np.float64, converters=conversores)
medias_sem_trocar_nan = np.mean(arr, axis=0).copy()
medias_nao_nan = np.mean(arr, axis=0)
medias_nan = [media for condicao, media in zip(colunas_com_nan, medias_nao_nan) if condicao]

for e, linha in enumerate(arr[:, colunas_com_nan]):
  for i, elem in enumerate(linha):
    if np.isnan(elem):
      arr[e] = medias_nan[i]

print(medias_sem_trocar_nan)
print(np.mean(arr, axis=0))

[5.81472928e-01 3.57282525e+01 1.67612779e+03 5.60020529e+00
            nan            nan 5.59917886e-01 3.84141647e-01
 3.19301976e+01]
[nan nan nan nan nan nan nan nan nan]


**f)** calcule agora a média, o desvio padrão, o máximo e o mínimo de todas as colunas do array sem filtro

In [7]:
print('Média:\n{}'.format(np.mean(arr, axis=0)))
print('Desvio padrão:\n{}'.format(np.std(arr, axis=0)))
print('Máximo:\n{}'.format(np.max(arr, axis=0)))
print('Mínimo:\n{}'.format(np.min(arr, axis=0)))

Média:
[nan nan nan nan nan nan nan nan nan]
Desvio padrão:
[nan nan nan nan nan nan nan nan nan]
Máximo:
[nan nan nan nan nan nan nan nan nan]
Mínimo:
[nan nan nan nan nan nan nan nan nan]


**2** Escreva duas funções, `get_rows` e `get_columns`, que recebem um array bidimensional como parâmetro. Elas devem retornar uma lista de linhas e colunas do array, respectivamente. As linhas e colunas devem ser matrizes unidimensionais. Você pode usar a operação de transposição, que inverte linhas para colunas, em sua solução. A transposição é feita pelo método `T`.

In [8]:
#exemplo
a=np.random.randint(0, 10, (4,4))
print(a)
print(a.T)

[[0 4 6 0]
 [7 9 5 8]
 [8 8 9 1]
 [9 6 2 9]]
[[0 7 8 9]
 [4 9 8 6]
 [6 5 9 2]
 [0 8 1 9]]


In [9]:
#exemplo
linhas = []
colunas = []
def get_rows(a):
  return [a]
linhas.append(a)
print(linhas)
def get_columns(a):
  return[a]
colunas.append(a.T)
print(colunas)

[array([[0, 4, 6, 0],
       [7, 9, 5, 8],
       [8, 8, 9, 1],
       [9, 6, 2, 9]])]
[array([[0, 7, 8, 9],
       [4, 9, 8, 6],
       [6, 5, 9, 2],
       [0, 8, 1, 9]])]


In [10]:
#solução
def get_rows(m):
    linhas = []
    for x in range(len(m)):
      linhas.append(np.array(m[x]))
    return linhas

In [11]:
#solução
def get_columns(m):
    colunas = []
    for x in range(len(m)):
      colunas.append(np.array(m.T[x]))
    return colunas

In [12]:
#teste - dados
a = np.array([[5, 0, 3, 3],
              [7, 9, 3, 5],
              [2, 4, 7, 6],
              [8, 8, 1, 6]])

In [13]:
#teste row
print(get_rows(a))
#[array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]

[array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]


In [14]:
#teste column
print(get_columns(a))
#[array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]

[array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]


**3** Crie a função `get_row_vectors` que retorna uma lista de linhas do array de entrada da forma `(n, m)`, mas desta vez as linhas devem ter a forma `(1, m)`. Da mesma forma, crie a função get_columns_vectors que retorne uma lista de colunas (cada uma com forma `(n, 1)`) da matriz de entrada.

Para a entrada:

`[[5 0 3]
 [3 7 9]]`
 
Deve ser gerada a saída:

Vetor de Linhas:

`[array([[5, 0, 3]]), array([[3, 7, 9]])]`

Vetor de Colunas:

`[array([[5],
        [3]]),
 array([[0],
        [7]]),
 array([[3],
        [9]])]`

In [15]:
#solucao row
def get_row_vectors(m):
  lista = []
  for lin in m:
    lista.append(np.array(lin).reshape(1, len(lin)))
  return lista

In [16]:
#solucao column
def get_column_vectors(m):
    m = m.T
    lista = []
    for lin in m:
        lista.append(np.array(lin).reshape(len(lin), 1))
    return lista

In [17]:
#teste - dados
a = np.array([[5, 0, 3],[3, 7, 9]])
a.shape

(2, 3)

In [18]:
#teste row
print(get_row_vectors(a))

[array([[5, 0, 3]]), array([[3, 7, 9]])]


In [19]:
#test column
print(get_column_vectors(a))

[array([[5],
       [3]]), array([[0],
       [7]]), array([[3],
       [9]])]


**4** Crie a função `diamante` que retorne um array inteiro bidimensional em que os 1s formem uma forma de diamante. O restante dos números é 0. A função deve receber um parâmetro que informe o comprimento de um lado do diamante. Faça isso usando as funções `eye` e `concatenate` do NumPy e o fatiamento de array.

Ex:

`print(diamante(3))`

`[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]`

`print(diamante(1))`

`[[1]]`

In [20]:
#Exemplo do concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
#Exemplo do concatenate
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [22]:
#Exemplo do concatenate
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [23]:
#solução
def diamante(n):
  lado_esq_cima = np.eye(n, dtype=int)[::-1]
  lado_dir_cima = np.eye(n, k=-1, dtype=int)[:, :-1]
  lado_esq_baixo = np.eye(n, k=1, dtype=int)[:-1]
  lado_dir_baixo = np.eye(n, k=-2, dtype=int)[::-1][:-1, :-1]

  lado_cima = np.concatenate((lado_esq_cima, lado_dir_cima), axis=1)
  lado_baixo = np.concatenate((lado_esq_baixo, lado_dir_baixo), axis=1)
  diamante = np.concatenate((lado_cima, lado_baixo), axis=0)
  return diamante

In [24]:
#teste
print(diamante(5))

[[0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 1 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0]]


In [25]:
#teste
print(diamante(1))

[[1]]


**5** Escreva a função lambda `so_pares` que receba um array unidimensional de inteiros e devolva este array sem números ímpares. Dica: use indexação booleana.

Ex:

Entrada: 

`arr = np.array([0,1,2,3,4,5,6,7,8,9])`

Saída:

`array([0, 2, 4, 6, 8])`

In [26]:
#solucao
so_pares = lambda a: a[a%2==0]

In [27]:
#teste
arr = np.arange(10)
so_pares(arr)

array([0, 2, 4, 6, 8])

**6** Escreva a função lambda `cade_os_iguais` que receba dois arrays unidimensionais de inteiros x e y e devolva um array com a(s) posição(ões) em que há números iguais nos dos arrays. Não use `for`. Dica: use np.where

Ex:

Entrada: 

`x = np.array([5,6,7,8,3,4])`

`y = np.array([5,3,4,5,2,4])`

Saída:

`array([0, 5])`

In [28]:
#solucao
cade_os_iguais = lambda x, y: np.where(x==y)

In [29]:
#teste
x = np.array([5,6,7,8,3,4])
y = np.array([5,3,4,5,2,4])

cade_os_iguais(x, y)

(array([0, 5], dtype=int32),)